// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_best_players = "CgkIqfrL3r0GEAIQAQ"; // <GPGSID>
        public const string achievement_five_and_alive = "CgkIqfrL3r0GEAIQBA"; // <GPGSID>
        public const string achievement_baby_ball = "CgkIqfrL3r0GEAIQAg"; // <GPGSID>
        public const string achievement_now_youre_just_showing_off = "CgkIqfrL3r0GEAIQBw"; // <GPGSID>
        public const string achievement_bouncy_ball = "CgkIqfrL3r0GEAIQBQ"; // <GPGSID>
        public const string achievement_king_ball = "CgkIqfrL3r0GEAIQBg"; // <GPGSID>
        public const string achievement_triple_terror = "CgkIqfrL3r0GEAIQAw"; // <GPGSID>

}

